import React, { useState } from "react";
import { AppProject } from "../types";
import { 
  Github, 
  RefreshCw, 
  GitBranch, 
  CheckCircle, 
  ExternalLink, 
  Lock, 
  Loader2, 
  Plus, 
  Globe, 
  Rocket 
} from "lucide-react";

interface GithubSyncProps {
  activeProject: AppProject | null;
  onUpdateProject: (p: AppProject) => void;
}

export default function GithubSync({
  activeProject,
  onUpdateProject
}: GithubSyncProps) {
  const [gitToken, setGitToken] = useState("");
  const [repoName, setRepoName] = useState(
    activeProject?.name.toLowerCase().replace(/\s+/g, "-") || ""
  );
  const [isPrivate, setIsPrivate] = useState(true);
  const [isConnecting, setIsConnecting] = useState(false);
  const [pushedOk, setPushedOk] = useState(false);
  const [releaseNotes, setReleaseNotes] = useState("");

  React.useEffect(() => {
    if (activeProject) {
      setRepoName(activeProject.name.toLowerCase().replace(/\s+/g, "-"));
    }
  }, [activeProject]);

  const handleConnect = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeProject || !repoName.trim()) return;

    setIsConnecting(true);
    setPushedOk(false);
    
    try {
      // Simulate OAuth handshakes and commit staging pushes
      await new Promise((resolve) => setTimeout(resolve, 2000));
      
      const updatedProject: AppProject = {
        ...activeProject,
        githubRepo: {
          owner: "surendraqwer41", // User Email owner prefix
          repoName: repoName,
          pushedAt: new Date().toISOString(),
          url: `https://github.com/surendraqwer41/${repoName}`,
          releases: ["v1.0.0-beta-release"]
        },
        buildLogs: [
          ...(activeProject.buildLogs || []),
          `[GIT] Connecting OAuth credentials with GitHub for profile: surendraqwer41`,
          `[GIT] Provisioned remote repository: surendraqwer41/${repoName}`,
          `[GIT] Committing source files: pubspec.yaml, main.dart, android files...`,
          `[GIT] Pushed payload to origin/main successfully with status 201 Created.`,
          `[GIT] Registered release hook tag: v1.0.0-beta-release`
        ]
      };

      onUpdateProject(updatedProject);
      setPushedOk(true);
      
      // Auto populate rich Release Notes with AI format
      setReleaseNotes(
        `## Release v1.0.0-beta-release \n\n* **App Manifest Profile:** ${activeProject.name}\n* **Target Platform:** Android SDK (API Level 34)\n* **Material Theme:** 3.0 configured accents\n* **Includes:** Autogenerated layout maps, MVVM controllers, direct compiler configurations.\n\n*Synced seamlessly via Auto App Publisher AI Workspace.*`
      );

    } catch (e) {
      console.error(e);
      alert("Failed connecting to remote repository. Review your local Personal Access Token.");
    } finally {
      setIsConnecting(false);
    }
  };

  const handleTriggerRelease = () => {
    alert("Drafting a new release directly into GitHub repository. APK assets attached.");
  };

  return (
    <div className="space-y-6" id="github-sync">
      
      {/* Title */}
      <div>
        <h2 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
          <Github className="w-6 h-6 text-purple-400" />
          GitHub Repository Integration Sync
        </h2>
        <p className="text-slate-400 text-sm mt-1">
          Bridge your generated source code folder structures directly with secure remote repositories to manage releases and source histories.
        </p>
      </div>

      {activeProject ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Credentials layout */}
          <div className="lg:col-span-5 bg-slate-900/40 rounded-2xl p-5 border border-slate-800 backdrop-blur-md h-fit space-y-4">
            <h3 className="font-bold text-slate-200 border-b border-slate-800 pb-3 mb-1 text-sm uppercase tracking-wide flex items-center gap-2">
              <Lock className="w-4 h-4 text-purple-400" />
              Repository Settings
            </h3>

            <form onSubmit={handleConnect} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5 uppercase font-mono">Personal Authentication Token</label>
                <input
                  type="password"
                  value={gitToken}
                  onChange={(e) => setGitToken(e.target.value)}
                  placeholder="github_pat_xxxx..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-slate-100 placeholder:text-slate-650 focus:outline-none focus:border-purple-500/50 font-mono"
                  required
                />
                <p className="text-[10px] text-slate-500 mt-1 leading-normal">
                  Requires <strong>repo</strong> scopes to allow automatic branch commits and draft releases.
                </p>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5 uppercase font-mono">Create Repository Name</label>
                <input
                  type="text"
                  value={repoName}
                  onChange={(e) => setRepoName(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-slate-100 placeholder:text-slate-650 focus:outline-none focus:border-purple-500/50 font-mono"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5 uppercase font-mono">Repository Privacy Scope</label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => setIsPrivate(true)}
                    className={`p-2.5 rounded-xl border font-semibold text-xs text-center transition-all cursor-pointer ${
                      isPrivate 
                        ? "bg-purple-900/10 border-purple-500 text-purple-300" 
                        : "bg-slate-950/40 border-slate-850 text-slate-400"
                    }`}
                  >
                    🔒 Private Repository
                  </button>
                  <button
                    type="button"
                    onClick={() => setIsPrivate(false)}
                    className={`p-2.5 rounded-xl border font-semibold text-xs text-center transition-all cursor-pointer ${
                      !isPrivate 
                        ? "bg-blue-900/10 border-blue-500 text-blue-300" 
                        : "bg-slate-950/40 border-slate-850 text-slate-400"
                    }`}
                  >
                    🌐 Public Repository
                  </button>
                </div>
              </div>

              <button
                type="submit"
                disabled={isConnecting}
                className="w-full py-3 px-4 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white font-bold text-sm tracking-wide shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer border border-white/10"
              >
                {isConnecting ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-purple-300" />
                    Connecting & Committing branches...
                  </>
                ) : (
                  <>
                    <Plus className="w-4 h-4" />
                    Push Source folder to GitHub
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Sync Connection Status info column */}
          <div className="lg:col-span-7 space-y-6">
            
            {activeProject.githubRepo ? (
              <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-5 backdrop-blur-md space-y-5">
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-green-400" />
                    <div>
                      <h4 className="font-bold text-slate-100 text-sm">GitHub Connector Live</h4>
                      <p className="text-[10px] text-slate-500 font-mono">Authenticated via Secure Oauth API</p>
                    </div>
                  </div>
                  <a
                    href={activeProject.githubRepo.url}
                    target="_blank"
                    rel="noreferrer"
                    className="text-xs font-bold text-purple-400 hover:text-purple-300 flex items-center gap-1.5 cursor-pointer"
                  >
                    Open Repository <ExternalLink className="w-3.5 h-3.5" />
                  </a>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-slate-950/80 p-3.5 rounded-xl border border-slate-900">
                    <span className="text-[9px] font-bold text-slate-500 block font-mono">TARGET BRANCH</span>
                    <span className="text-xs font-bold text-slate-300 mt-1 block flex items-center gap-1.5">
                      <GitBranch className="w-3.5 h-3.5 text-blue-400" />
                      origin/main
                    </span>
                  </div>

                  <div className="bg-slate-950/80 p-3.5 rounded-xl border border-slate-900">
                    <span className="text-[9px] font-bold text-slate-500 block font-mono">SYNC STATUS</span>
                    <span className="text-xs font-bold text-green-400 mt-1 block">
                      ● Code up to date
                    </span>
                  </div>
                </div>

                {/* Release creation module */}
                <div className="space-y-3 pt-2">
                  <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wide font-mono">Draft Release Notes Output</h4>
                  <textarea
                    value={releaseNotes}
                    onChange={(e) => setReleaseNotes(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-900 rounded-xl px-3.5 py-3 text-xs text-slate-300 h-44 resize-none font-mono focus:outline-none custom-scrollbar"
                  />
                  <div className="flex justify-between items-center bg-slate-950/50 p-2.5 rounded-xl border border-slate-900">
                    <p className="text-[10px] text-slate-500">Includes auto-pushed compilation assets: APK/AAB</p>
                    <button
                      onClick={handleTriggerRelease}
                      className="bg-purple-600 hover:bg-purple-500 text-white font-bold text-xs px-4 py-2 rounded-lg transition-all flex items-center gap-1.5 cursor-pointer"
                    >
                      <Rocket className="w-3.5 h-3.5" />
                      Release package v1.0.0
                    </button>
                  </div>
                </div>

              </div>
            ) : (
              <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-8 flex flex-col items-center justify-center text-center h-full backdrop-blur-md">
                <Lock className="w-12 h-12 text-slate-755 mb-3" />
                <h4 className="text-md font-bold text-slate-350">Commit Terminal Offline</h4>
                <p className="text-xs text-slate-400 mt-1 max-w-sm leading-relaxed">
                  Provide your Personal Authentication Token in the credential panel on the left to push code to GitHub and deploy releases.
                </p>
              </div>
            )}

          </div>

        </div>
      ) : (
        <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-12 text-center">
          <p className="text-slate-400 text-sm">Create or choose an active workspace project first.</p>
        </div>
      )}
    </div>
  );
}
